"""
Exports the 12 production LightGBM models to plain JavaScript (m2cgen) --
a direct code transliteration of each tree's if/else logic, not a semantic
re-encoding like ONNX's TreeEnsemble op. Verified empirically to reproduce
LightGBM's predictions EXACTLY, unlike onnxmltools' ONNX conversion which
showed real (non-precision) drift up to ~0.011 log-price-points on 5 of 12
models -- see MANIFEST-style note in web/backend/src/models/README.md for
the full account.

Also dumps a cross-language validation fixture (sample feature vectors +
Python ground-truth predictions) for the Node-side parity test to check
against.

FIXED 2026-09-13 (train/serve skew, same bug as Script 24's dashboard
predict()): the fixture used to compute its Python "ground truth" by
calling model.predict(X) on X still carrying real NaN (reference_rows.csv
genuinely has NaN in several feature columns for thinner-history markets)
-- so the old fixture only verified that the JS's native NaN-routing
matched Python's OWN native NaN-routing, never that either matched what
the model was actually TRAINED to see. Script 23 applies fillna(0) before
every training fit, so the model never saw a real NaN during training at
all; whatever NaN-default-split-direction m2cgen transliterates was never
meaningfully learned. Now applies the same fillna(0) here before both
computing py_pred and storing the fixture's input vector, so the fixture
(and the production JS backend, fixed the same way in
backend/src/models/index.js's toNumeric()) actually reflect the trained
convention.

Run: python generate_js_models.py
Then: node backend/src/models/__fixtures__/verify.mjs
"""
import os
import json
import joblib
import pandas as pd
import m2cgen as m2c

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(BASE, 'Model_Output', 'production_models')
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'backend', 'src', 'models')
os.makedirs(OUT_DIR, exist_ok=True)

FIXTURE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'backend', 'src', 'models', '__fixtures__')
os.makedirs(FIXTURE_DIR, exist_ok=True)

CROPS = ['tomato', 'onion', 'potato']
HORIZONS = [1, 4, 13, 26]
N_FIXTURE_SAMPLES = 200

with open(os.path.join(MODEL_DIR, 'feature_columns.json'), encoding='utf-8') as f:
    feature_columns = json.load(f)

reference = pd.read_csv(os.path.join(MODEL_DIR, 'reference_rows.csv'))

index = {}
for crop in CROPS:
    for h in HORIZONS:
        key = f'{crop}_{h}w'
        model_path = os.path.join(MODEL_DIR, f'{key}.joblib')
        if not os.path.exists(model_path):
            continue
        print(f'=== {key} ===')
        model = joblib.load(model_path)
        cols = feature_columns[key]

        js_body = m2c.export_to_javascript(model)
        # m2cgen emits a single top-level `function score(input) { ... }`
        # (verified: no helper sub-functions even for 133-tree models) --
        # rename in place to a unique exported name so each file is a
        # self-contained ES module with no global collisions. Body is left
        # byte-for-byte untouched (only the function signature line changes)
        # to avoid any risk of corrupting the transliterated tree logic.
        assert js_body.count('function score(input)') == 1, f'{key}: unexpected m2cgen output shape'
        js_module = (
            f"// AUTO-GENERATED by web/generate_js_models.py from {key}.joblib -- do not hand-edit.\n"
            f"// Exact transliteration of the trained LightGBM model's tree logic (m2cgen).\n"
            + js_body.replace('function score(input)', f'export function predict_{key}(input)', 1)
        )
        out_path = os.path.join(OUT_DIR, f'{key}.js')
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(js_module)
        print(f'  wrote {out_path} ({len(js_module)} chars)')

        # ── Fixture: sample rows + Python ground truth (log-price output) ──
        crop_rows = reference[reference['crop'] == crop]
        sample = crop_rows.sample(n=min(N_FIXTURE_SAMPLES, len(crop_rows)), random_state=7)
        fixture = []
        for _, row in sample.iterrows():
            feat = {c: row.get(c) for c in cols}
            X = pd.DataFrame([feat])
            for c in X.columns:
                X[c] = pd.to_numeric(X[c], errors='coerce')
            # FIXED 2026-09-13: ground truth used to be computed from X
            # WITH real NaN still present, so this fixture only ever
            # verified the JS's native NaN-routing against Python's own
            # native NaN-routing -- neither matches what the model was
            # actually TRAINED on, since Script 23 applies fillna(0)
            # before every training fit. fillna(0) here makes the fixture
            # (and therefore verify.mjs) test the input the model was
            # actually trained to see, matching Script 23/24's convention.
            X = X.fillna(0)
            py_pred = float(model.predict(X)[0])
            xvals = X.iloc[0].tolist()
            fixture.append({'input': xvals, 'expected': py_pred})

        fixture_path = os.path.join(FIXTURE_DIR, f'{key}.json')
        with open(fixture_path, 'w', encoding='utf-8') as f:
            json.dump(fixture, f)
        print(f'  wrote fixture {fixture_path} ({len(fixture)} rows)')

        index[key] = {'cols': cols}

index_path = os.path.join(OUT_DIR, 'feature_columns.json')
with open(index_path, 'w', encoding='utf-8') as f:
    json.dump(feature_columns, f, indent=1)
print(f'\nWrote {index_path}')
print('\nDone. Run `node backend/src/models/__fixtures__/verify.mjs` next to cross-check in Node.')
